# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shamir < Formula
  desc "Split and combine secrets using Shamir's Secret Sharing algorithm."
  homepage "https://incipher.io/shamir"
  version "0.6.0"
  license "CC0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/incipher/shamir/releases/download/v0.6.0/shamir_0.6.0_Darwin_arm64.tar.gz"
      sha256 "3c8a280a11d5b074ea21bf1bb5ad3ff696eb3e2bef6174b4341b90bdb84cfc44"

      def install
        bin.install "shamir"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/incipher/shamir/releases/download/v0.6.0/shamir_0.6.0_Darwin_x86_64.tar.gz"
      sha256 "a777d8815c1f600420c340722bcbc40f46e7d52e5cbc88f2d923e7faf0073905"

      def install
        bin.install "shamir"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/incipher/shamir/releases/download/v0.6.0/shamir_0.6.0_Linux_arm64.tar.gz"
      sha256 "62730b10754e4b70d26b1bf587e50858cd6ae00fe333234f87502bf5ba923274"

      def install
        bin.install "shamir"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/incipher/shamir/releases/download/v0.6.0/shamir_0.6.0_Linux_x86_64.tar.gz"
      sha256 "8b2982f57aaca9955716d2e2f5769af9a6175023136b119d72ae5fd982f528ca"

      def install
        bin.install "shamir"
      end
    end
  end

  test do
    system "#{bin}/shamir --version"
  end
end
