# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shamir < Formula
  desc "Split and combine secrets using Shamir's Secret Sharing algorithm."
  homepage "https://incipher.io/shamir"
  version "v0.1.1"
  license "CC0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/incipher/shamir/releases/download/v0.1.1/shamir_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "120e01ac60cfb1bde4f493738a68790b9418ecfc22dd424e6ba511f364984795"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/incipher/shamir/releases/download/v0.1.1/shamir_0.1.1_Darwin_arm64.tar.gz"
    sha256 "2c0d60545125a8333ef0202cfe3347d1840a19e5f42059ced0bbe9aa0e78899d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/incipher/shamir/releases/download/v0.1.1/shamir_0.1.1_Linux_x86_64.tar.gz"
    sha256 "c51d3d226fa8798c6c56e56947f8a72430ca9c3885bfe3896c94cdf91756c4f1"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/incipher/shamir/releases/download/v0.1.1/shamir_0.1.1_Linux_arm64.tar.gz"
    sha256 "0ca67911428d4568abc719b6fed20174de75045bc645e51b5d426911331351ed"
  end

  depends_on "go"

  def install
    bin.install "shamir"
  end

  test do
    system "#{bin}/shamir --version"
  end
end
