# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shamir < Formula
  desc "Split and combine secrets using Shamir's Secret Sharing algorithm."
  homepage "https://incipher.io/shamir"
  version "0.4.2"
  license "CC0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/incipher/shamir/releases/download/v0.4.2/shamir_0.4.2_Darwin_x86_64.tar.gz"
      sha256 "31ba64e04408c7f8e8be9857544ae3f7af0820e216e35a365614d29745998a47"

      def install
        bin.install "shamir"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/incipher/shamir/releases/download/v0.4.2/shamir_0.4.2_Darwin_arm64.tar.gz"
      sha256 "8444ae80b53db70f42787b4c5e431b01cc2c9119c904921e0a0dfa886b8f4b96"

      def install
        bin.install "shamir"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/incipher/shamir/releases/download/v0.4.2/shamir_0.4.2_Linux_arm64.tar.gz"
      sha256 "efcaf8eafd1bc55a578ed528587263a4da5c1dea5b7a96742a980b375af955c7"

      def install
        bin.install "shamir"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/incipher/shamir/releases/download/v0.4.2/shamir_0.4.2_Linux_x86_64.tar.gz"
      sha256 "ee99a68fc7f7dfd88fde37e57847934b7b48afbaa848bb2caa9b3c83c4f08740"

      def install
        bin.install "shamir"
      end
    end
  end

  test do
    system "#{bin}/shamir --version"
  end
end
